In [1]:
import pandas as pd
import csv, json

In [3]:
# read in csv file
draft = pd.read_csv("DraftProbabilities.csv")
clean2022 = pd.read_csv("Cleaned2022.csv")

In [4]:
draft.head()

   id  Nodraft  Yesdraft               Player                Team Conference
0   0    1.000     0.000        Isaiah Felder  South Carolina St.       MEAC
1   1    0.984     0.016  Jalen Coleman-Lands              Kansas        B12
2   2    0.980     0.020          K.J. Walton               Akron        MAC
3   3    0.980     0.020         Jeriah Horne               Tulsa       Amer
4   4    0.998     0.002           Eric Curry           Minnesota        B10

In [5]:
clean2022.head()

,Unnamed: 0,Unnamed: 0.1,player_name,team,conf,GP,Min_per,Ortg,usg,eFG,...,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,Unnamed: 64,Unnamed: 65
0,0,0,Isaiah Felder,South Carolina St.,MEAC,11,17.6,61.1,18.6,34.7,...,-4.412530,0.2727,1.4545,1.7273,0.4545,0.1818,0.0000,2.3636,Wing G,12.226400
1,1,1,Jalen Coleman-Lands,Kansas,B12,23,78.5,103.1,21.5,54.0,...,-1.019000,1.0435,2.8696,3.9130,1.1739,0.8261,0.0870,14.3043,Wing G,11.095900
2,2,2,K.J. Walton,Akron,MAC,20,63.0,108.6,26.5,54.3,...,-0.335789,2.3500,3.5500,5.9000,1.1500,1.2500,0.2000,16.3500,Wing G,0.284581
3,3,3,Jeriah Horne,Tulsa,Amer,32,61.3,116.0,20.8,55.2,...,1.721580,1.1250,4.7188,5.8438,0.9062,0.5938,0.0625,10.8125,Stretch 4,10.140700
4,4,4,Eric Curry,Minnesota,B10,29,39.2,95.1,14.7,46.3,...,2.746770,1.1034,1.9655,3.0690,0.8276,0.8276,0.2414,3.6552,Wing F,2.562430

In [6]:
# add columns to draft dataframe
# "GP", "Min_per", "Ortg", "TS_per", "AST_per", "TO_per", "blk_per", "FT_per", "porpag", "adjoe"
draft["Games Played"] = clean2022["GP"]
draft["Minutes Percentage"] = clean2022["Min_per"]
draft["Offensive Rating"] = clean2022["Ortg"]
draft["True Shooting Percentage"] = clean2022["TS_per"]
draft["Assist Percentage"] = clean2022["AST_per"]
draft["Turnover Percentage"] = clean2022["TO_per"]
draft["Block Percentage"] = clean2022["blk_per"]
draft["Free Throw Percentage"] = clean2022["FT_per"]
draft["Points Over Replacement Per Adjusted Game"] = clean2022["porpag"]
draft["Adjusted Offensive Efficiency"] = clean2022["adjoe"]
draft.head()

,id,Nodraft,Yesdraft,Player,Team,Conference,Games Played,Minutes Percentage,Offensive Rating,True Shooting Percentage,Assist Percentage,Turnover Percentage,Block Percentage,Free Throw Percentage,Points Over Replacement Per Adjusted Game,Adjusted Offensive Efficiency
0,0,1.000,0.000,Isaiah Felder,South Carolina St.,MEAC,11,17.6,61.1,35.18,8.1,30.4,0.0,0.500,-1.110000,57.5491
1,1,0.984,0.016,Jalen Coleman-Lands,Kansas,B12,23,78.5,103.1,56.12,7.8,16.1,0.3,0.861,2.977030,111.4260
2,2,0.980,0.020,K.J. Walton,Akron,MAC,20,63.0,108.6,58.88,8.9,17.2,0.7,0.793,3.097360,116.1010
3,3,0.980,0.020,Jeriah Horne,Tulsa,Amer,32,61.3,116.0,58.61,7.5,13.0,0.3,0.906,3.277890,123.8120
4,4,0.998,0.002,Eric Curry,Minnesota,B10,29,39.2,95.1,48.72,10.2,20.7,1.5,0.621,0.435561,93.2541

In [7]:
# creating csv from possible drafted 2022 players dataframe
draft.to_csv("Complete2022Draft.csv")

In [8]:
# file paths
csvDraft = 'Complete2022Draft.csv'
jsonDraft = 'draft.json'

In [9]:
# read csv file and add to data
data = {}
with open(csvDraft) as  csvFile:
    csvReader = csv.DictReader(csvFile)
    for rows in csvReader:
        id = rows['id']
        data[id] = rows

In [10]:
# create json file and write data on it
with open(jsonDraft, 'w') as jsonFile:
    # pretty data
    jsonFile.write(json.dumps(data, indent=4))