In [1]:
from matplotlib import pyplot as plt
from sklearn.datasets import make_classification
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [2]:
df = pd.read_csv("Resources/Final_new_draft.csv")
df

,Unnamed: 0,player_name,team_x,conf,GP,Min_per,Ortg,usg,eFG,TS_per,...,stl,blk,pts,Unnamed: 64,Unnamed: 65,nba team,team_y,year_y,ROUND NUMBER,ROUND PICK
0,0,DeAndrae Ross,South Alabama,SB,26,29.5,97.3,16.6,42.5,44.43,...,0.3462,0.0385,3.8846,NaN,6.22026,NaN,NaN,NaN,NaN,NaN
1,1,DeAndrae Ross,Troy,SB,7,11.5,67.1,16.9,34.5,36.11,...,0.1429,0.0000,3.2857,Wing G,7.67089,NaN,NaN,NaN,NaN,NaN
2,2,Pooh Williams,Utah St.,WAC,34,60.9,108.3,14.9,52.4,54.48,...,0.4118,0.2353,5.9412,NaN,3.94375,NaN,NaN,NaN,NaN,NaN
3,3,Pooh Williams,Utah St.,WAC,32,64.0,108.3,18.1,53.0,53.33,...,0.5938,0.2188,8.7812,Combo G,7.30085,NaN,NaN,NaN,NaN,NaN
4,4,Pooh Williams,Utah St.,WAC,33,64.5,105.6,18.7,48.1,52.40,...,0.2121,0.0909,8.6667,Combo G,9.66297,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61066,61066,Kamron Battle,Northern Illinois,MAC,2,0.5,0.0,0.0,0.0,0.00,...,0.0000,0.0000,0.0000,PF/C,0.00000,NaN,NaN,NaN,NaN,NaN
61067,61067,Stavros Polatoglou,Northwestern St.,Slnd,4,1.3,28.3,7.1,0.0,0.00,...,0.0000,0.0000,0.0000,C,0.00000,NaN,NaN,NaN,NaN,NaN
61068,61068,Sandy Ryan,Tulane,Amer,1,0.1,0.0,0.0,0.0,0.00,...,0.0000,0.0000,0.0000,PF/C,0.00000,NaN,NaN,NaN,NaN,NaN
61069,61069,Ty Larson,Texas Tech,B12,1,0.1,0.0,0.0,0.0,0.00,...,0.0000,0.0000,0.0000,PF/C,0.00000,NaN,NaN,NaN,NaN,NaN
61070,61070,Jaden Jones,Rutgers,B10,4,1.0,89.6,28.8,25.0,25.00,...,0.0000,0.0000,0.7500,Pure PG,10.43920,NaN,NaN,NaN,NaN,NaN

In [3]:
#draftstatus= df['draft_status']
#draftstatus.replace["Undrafted" : 0, inplace=True]
#draftstatus.replace["Drafted" : 1, ]

In [4]:
df.loc[df['draft_status'] == "Undrafted", 'draft_status'] = 0
df.loc[df['draft_status'] == "Drafted", 'draft_status'] = 1
df['draft_status'].head(78)

0     0
1     0
2     0
3     0
4     0
     ..
73    1
74    1
75    1
76    0
77    0
Name: draft_status, Length: 78, dtype: object

In [20]:
#newdf = df['draft_status'].astype(int)
#newdf.dtypes

dtype('int32')

In [21]:
droppedstats =df.dropna(axis=0, subset=["pts", "treb", "ast", "stl", "blk","ast/tov", "mp", "FT_per", "eFG"])
droppedstats

,Unnamed: 0,player_name,team_x,conf,GP,Min_per,Ortg,usg,eFG,TS_per,...,stl,blk,pts,Unnamed: 64,Unnamed: 65,nba team,team_y,year_y,ROUND NUMBER,ROUND PICK
0,0,DeAndrae Ross,South Alabama,SB,26,29.5,97.3,16.6,42.5,44.43,...,0.3462,0.0385,3.8846,NaN,6.22026,NaN,NaN,NaN,NaN,NaN
1,1,DeAndrae Ross,Troy,SB,7,11.5,67.1,16.9,34.5,36.11,...,0.1429,0.0000,3.2857,Wing G,7.67089,NaN,NaN,NaN,NaN,NaN
2,2,Pooh Williams,Utah St.,WAC,34,60.9,108.3,14.9,52.4,54.48,...,0.4118,0.2353,5.9412,NaN,3.94375,NaN,NaN,NaN,NaN,NaN
3,3,Pooh Williams,Utah St.,WAC,32,64.0,108.3,18.1,53.0,53.33,...,0.5938,0.2188,8.7812,Combo G,7.30085,NaN,NaN,NaN,NaN,NaN
4,4,Pooh Williams,Utah St.,WAC,33,64.5,105.6,18.7,48.1,52.40,...,0.2121,0.0909,8.6667,Combo G,9.66297,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61058,61058,Jordan Nesbitt,Memphis,Amer,3,1.0,50.3,30.1,37.5,37.50,...,0.0000,0.0000,1.0000,Stretch 4,15.41270,NaN,NaN,NaN,NaN,NaN
61059,61059,Quinn Pemberton,Boston College,ACC,2,0.9,0.0,13.8,0.0,0.00,...,0.0000,0.0000,0.0000,Combo G,7.69879,NaN,NaN,NaN,NaN,NaN
61060,61060,Mac Etienne,UCLA,P12,13,11.0,99.1,15.1,60.0,55.37,...,0.1538,0.1538,2.6154,C,0.00000,NaN,NaN,NaN,NaN,NaN
61062,61062,Lysander Rehnstrom,George Mason,A10,2,0.3,0.0,32.2,0.0,0.00,...,0.0000,0.0000,0.0000,PF/C,22.22830,NaN,NaN,NaN,NaN,NaN
61067,61067,Stavros Polatoglou,Northwestern St.,Slnd,4,1.3,28.3,7.1,0.0,0.00,...,0.0000,0.0000,0.0000,C,0.00000,NaN,NaN,NaN,NaN,NaN

In [25]:
newdf = droppedstats['draft_status'].astype(int)
#newdf

In [26]:
stats = ["pts", "treb", "ast", "stl", "blk","ast/tov", "mp", "FT_per", "eFG"]
X = droppedstats[stats]
y= newdf

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [29]:
rcf = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_train_scaled, y_train)
score1= rcf.score(X_train_scaled, y_train)
score2 =rcf.score(X_test_scaled, y_test)
print(score1)

1.0

In [30]:
print(score2)

0.9734488144256709

In [ ]:
fresh = df.loc[df['yr']=="Fr"]
soph = df.loc[df['yr']=="So"]
junior = df.loc[df['yr']=="Jr"]
senior = df.loc[df['yr']=="Sr"]

In [ ]:
model = KMeans(n_clusters=2, random_state=5)
model.fit(fresh)